name: Cypress Cloud

on:
  workflow_dispatch: 
    inputs: 
      cli:
        description: Run by cypress command line
        default: yarn client
jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-comman: yarn install
          browser: electron 
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env: 
          CYPRESS_RECORD_KEY: 79656fd5-afd3-40cc-8039-70fa604383ff
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    
          
          
        
        
