name: Cypress Tests

on:
  workflow_dispatch: 
    inputs: 
      cli:
        description: Run by cypress command line
        default: yarn client
jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.1

      - name: Install dependencies
        run: yarn install

      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}
