name: Cypress Tests

on:
  workflow_dispatch: 
    inputs: 
      cli:
        description: Run by cypress command line
        default: yarn client
jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    env:
      TESULTS_TOKEN: ${{ secrets.TESULTS_TOKEN }}
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.1

      - name: Clear Yarn Cache
        run: yarn cache clean

      - name: Install dependencies
        run: yarn install

      - name: Install Tesults
        run: yarn add cypress-tesults --dev
        env:
          TESULTS_TOKEN: ${{ secrets.TESULTS_TOKEN }}

      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}

      - name: Run E2E tests with Tesults reporter
        run: npx cypress run --config reporterOptions.token=${TESULTS_TOKEN} ${{ github.event.inputs.cli }}
